### ISSUE TITLE
Getting runtime error.

### ISSUE THREAD

**Issue by abhinavsp0730** [Ki6an/fastT5#1]
Hi, @Ki6an  it's great work. But while executing below code
```
from fastT5 import export_and_get_onnx_model
from transformers import AutoTokenizer

model_name = 't5-small'
model = export_and_get_onnx_model(model_name)

tokenizer = AutoTokenizer.from_pretrained(model_name)
t_input = "translate English to French: The universe is a dark forest."
token = tokenizer(t_input, return_tensors='pt')

tokens = model.generate(input_ids=token['input_ids'],
               attention_mask=token['attention_mask'],
               num_beams=2)

output = tokenizer.decode(tokens.squeeze(), skip_special_tokens=True)
print(output)
```
I'm getting this error.
```
RuntimeError: output with shape [5, 12, 1, 2] doesn't match the broadcast shape [5, 12, 2, 2]


```

**Comment by Ki6an** [comment]
@abhinavsp0730 that's a known issue in transformers library while exporting t5 to onnx. the issue can be fixed by following the guide in this [notebook](https://colab.research.google.com/drive/1HuH1Ui3pCBS22hW4djIOyUBP5UW93705?usp=sharing).

or you can make the following changes in the `modeling_t5.py` file of your local transformers library  and **save** it:

![image](https://user-images.githubusercontent.com/63173962/111636277-54eac300-881e-11eb-8f4e-53b996c19f73.png)


I've already created PR for this issue [here ](https://github.com/huggingface/transformers/pull/10651)

**Comment by abhinavsp0730** [comment]
@Ki6an thanks for the help. Is this method is supported for GPU or CPU?

**Comment by abhinavsp0730** [comment]
> @Ki6an thanks for the help. Is this method is supported for GPU or CPU?

I'm guessing it's not using onnxruntime-gpu package.So is fastT5 compatable with Gpu if we install 
onnxruntime-gpu in place of onnxruntime?

**Comment by Ki6an** [comment]
@abhinavsp0730 currently fastT5 doesn't support GPU yet, will be working on this in the future.
`onnxruntime-gpu` doesn't support  `quantization` & for the onnx model to perform better than the PyTorch models on GPU need to implement [IObinding](https://www.onnxruntime.ai/python/api_summary#iobinding).
